@startuml Workout Planner
header User App Flow
Title "Typical Workflow Chart"
skinparam actorstyle awesome
skinparam RectangleBorderColor SteelBlue
"Initial Login" as (fUse) #PaleGreen;line:green;text:blue
"Recurrent Login" as (rUse)
:Drae: as user #SteelBlue;line:blue;
user --> (rUse)

rectangle "First Time Setup" #AliceBlue{

user --> (fUse)

fUse -left-> (Create Account)
(Create Account) --> (Create Goals)

note left : Provide the user with the option to\nview a set of guidelines for creating a\nquality goal

(Create Goals) --> (Starting Point)
note left : Basic assessment

(Starting Point) --> (Set Milestones)

} 

(Set Milestones) ---> (Common Choices)


(rUse) --> (Review Milestones)
note right : Update\nGoals if needed
(Review Milestones) --> (Common Choices) 

rectangle "Common Features"{

    (Plan My Workout)
    (Check my Progress)
    (Plan My Meal)
}

(Common Choices) --> (Plan My Workout)
(Common Choices) --> (Check my Progress)
(Common Choices) --> (Plan My Meal)

@enduml